Freezers3/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'Freezers3.views.root_view', name='home'),
    url(r'^accounts/login/$', login),
    url(r'^accounts/logout/$', 'Freezers3.views.logout_view'),
    url(r'^freezers/', include('freezers.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT}),
    )
    urlpatterns += patterns('',
        url(r'^resources/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )
urlpatterns += staticfiles_urlpatterns()

freezers/urls.py
from django.conf.urls.defaults import patterns  # , include, url

urlpatterns = patterns(
    'freezers.views',
    (r'^$', 'freezer_index'),
    (r'^new/$', 'add_freezer'),
    (r'^(?P<freezer_id>\d+)/select-location/$', 'select_sample_location'),
    (r'^(?P<freezer_id>\d+)/select-sample-location/$',
        'select_sample_location'),
    (r'^(?P<freezer_id>\d+)/(?P<address>\d+)/$', 'show_box'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/$',
        'select_box_location'),
    (r'^(?P<freezer_id>\d+)/add-samples/$', 'add_samples_to_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/add-samples/$',
        'add_samples_to_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/add-samples/$',
        'add_samples_to_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/add-samples/$',
        'add_samples_to_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/(?P<cell_id>\d+)/add-samples/$',
        'add_samples_to_freezer'),
    (r'^(?P<freezer_id>\d+)/samples/$', 'sample_index_by_location'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/samples/$',
     'sample_index_by_location'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/samples/$',
     'sample_index_by_location'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/samples/$',
        'sample_index_by_location'),
    (r'^samples/$', 'sample_index'),
    (r'^suppliers/new/$', 'add_supplier'),
    (r'^suppliers/$', 'supplier_index'),
    (r'^sample-type/new/$', 'add_sample_type'),
    (r'^(?P<freezer_id>\d+)/$', 'freezer_detail'),
    (r'^suppliers/(?P<supplier_id>\d+)/$', 'supplier_detail'),
    (r'^samples/(?P<sample_id>\d+)/$', 'sample_detail'),
    (r'^(?P<freezer_id>\d+)/edit/$', 'edit_freezer'),
    (r'^(?P<freezer_id>\d+)/remove/$', 'remove_freezer'),
    (r'^suppliers/(?P<supplier_id>\d+)/edit/$', 'edit_supplier'),
    (r'^samples/(?P<sample_id>\d+)/edit/$', 'edit_sample'),
    (r'^samples/(?P<sample_id>\d+)/move/$', 'move_sample_select_freezer'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/(?P<cell_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/move-box/$',
        'move_box_select_freezer'),
    (r'(?P<box_address>\d+)/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/move-box/$',
        'move_box'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/rearrange-samples/$',
        'rearrange_samples_within_box'),
    (r'^samples/(?P<sample_id>\d+)/(?P<cell_id>\d+)/swap-samples/$', 'swap_samples'),
    (r'^samples/(?P<sample_id>\d+)/remove/$', 'remove_sample_from_index'),
    (r'^samples/(?P<sample_id>\d+)/remove-sample/$', 'remove_sample'),
    (r'^search/$', 'search'),
    (r'^(?P<freezer_id>\d+)/select-region-to-edit/$',
        'select_region_to_edit'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/edit-region/$',
        'edit_freezer_region'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/edit-region/$',
        'edit_freezer_region'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/edit-region/$',
        'edit_freezer_region'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/edit-region/$',
        'edit_freezer_region'),
    (r'^removed/((?P<query>[^/]+)/)?$', 'removed_index'),
    (r'^removed/(?P<removed_id>\d+)/detail/$', 'removed_detail'),
    (r'^removed/(?P<removed_id>\d+)/return/$', 'return_removed_sample'),
    (r'^home/$', 'home_link'),
    (r'^home/(?P<user_id>\d+)/$', 'homepage'),
    (r'^messages/(?P<msg_id>\d+)/delete/$', 'delete_message'),
    (r'^messages/(?P<msg_id>\d+)/reply/$', 'reply_to_message'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/select-samples/$',
        'select_samples_in_box'),
    (r'^move-selected/$',
        'move_selected_samples_select_freezer'),
    (r'^move-selected/(?P<freezer_id>\d+)/$',
        'move_selection'),
    (r'^move-selected/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/$',
        'move_selection'),
    (r'^move-selected/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/$',
        'move_selection'),
    (r'^move-selected/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/$',
        'move_selection'),
    (r'^move-selected/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/$',
        'move_selection'),
    (r'^move-selected/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/(?P<cell_id>\d+)/$',
        'move_selection'),
    (r'^remove-selected-samples/$', 'remove_selected_samples'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/remodel/$',
        'remodel_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/remodel/$',
        'remodel_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/remodel/$',
        'remodel_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/remodel/$',
        'remodel_freezer'),
    (r'^export-samples/$', 'export_samples'),
    (r'^delete-file/(?P<file_id>\d+)/$', 'delete_file'),
    (r'^(?P<freezer_id>\d+)/(?P<addr>\d+)/name-box/$', 'name_box'),
)

freezers/models.py
from datetime import datetime
from django.db import models, connection, transaction
from django.forms import ModelForm
from django import forms
from django.contrib.localflavor.us.models import PhoneNumberField
from django.contrib.auth.models import User
from freezers.utilities import getaddress, getposition


class Freezer(models.Model):
    FREEZER_KIND_CHOICES = (
        (u'liq. N\u2082', u'liq. N\u2082'),
        (u'\u221280 \u2103', u'\u221280 \u2103'),
        (u'\u221220 \u2103', u'\u221220 \u2103'),
        (u'4 \u2103', u'4 \u2103'),
    )
    # Location/identification
    building_room_number = models.CharField(max_length=100, help_text="*")
    kind = models.CharField(max_length=10, choices=FREEZER_KIND_CHOICES,
                            help_text="*")
    model = models.CharField(max_length=100, help_text="*")

    # Product information
    manufacturer = models.CharField(blank=True, max_length=100)
    product_number = models.CharField(blank=True, max_length=100)
    serial_number = models.CharField(blank=True, max_length=100)
    phone_number = PhoneNumberField(blank=True)

    # Initial freezer capacity
    shelf_capacity = models.IntegerField(help_text="* shelves/freezer")
    rack_capacity = models.IntegerField(help_text="* racks/shelf")
    drawer_capacity = models.IntegerField(help_text="* drawers/rack")
    box_capacity = models.IntegerField(help_text="* boxes/drawer")
    box_width = models.IntegerField(help_text="* a box dimension")
    cell_capacity = models.IntegerField(help_text="* cells/box")

    # Space accounting
    unoccupied = models.IntegerField(blank=True)
    occupied = models.IntegerField(blank=True)
    percent_free = models.FloatField(blank=True)

    @transaction.autocommit
    def save(self, *args, **kwargs):
        """
        Override save such that creation of a freezer generates samplelocation
        entries corresponding to the freezer.
        """
        self.occupied = 0
        self.unoccupied = (self.shelf_capacity *
                           self.rack_capacity *
                           self.drawer_capacity *
                           self.box_capacity *
                           self.cell_capacity)
        self.percent_free = 0.0
        super(Freezer, self).save(*args, **kwargs)
        cur = connection.cursor()
        t = [(False, self.id, getaddress((s, r, d, b, c)),
              self.box_width, self.cell_capacity)
             for s in xrange(1, self.shelf_capacity + 1)
             for r in xrange(1, self.rack_capacity + 1)
             for d in xrange(1, self.drawer_capacity + 1)
             for b in xrange(1, self.box_capacity + 1)
             for c in xrange(1, self.cell_capacity + 1)]
        cur.executemany("""INSERT INTO freezers_samplelocation (occupied,
            freezer_id, address, box_width, cell_capacity)
            values (%s, %s, %s, %s, %s)""", t)
        transaction.commit()

    def calc_occupied(self, *args, **kwargs):
        """
        Calculate the free, occupied and total number of samplelocations
        associated with this freezer.
        """
        cur = connection.cursor()
        cur.execute("""SELECT COUNT(*) FROM freezers_samplelocation
                       WHERE freezer_id = %s AND occupied IS NOT
                       NULL""" % self.id)
        t = float(cur.fetchone()[0])
        cur.execute("""SELECT COUNT(*) FROM freezers_samplelocation WHERE
                    freezer_id = %s AND occupied = False""" % self.id)
        self.unoccupied = int(cur.fetchone()[0])
        cur.execute("""SELECT COUNT(*) FROM freezers_samplelocation WHERE
                    freezer_id = %s AND occupied = True""" % self.id)
        self.occupied = int(cur.fetchone()[0])
        self.percent_free = self.unoccupied / t * 100
        super(Freezer, self).save(*args, **kwargs)

    def attrsave(self, *args, **kwargs):
        """
        A save method that doesn't affect sample location data.
        """
        super(Freezer, self).save(*args, **kwargs)

    def __unicode__(self):
        return u"%s, %s %s %s" % (self.building_room_number,
                                  self.manufacturer,
                                  self.model,
                                  self.kind)


class FreezerForm(ModelForm):

    def clean(self):
        """
        Custom validation to ensure user input is correct.
        """
        super(FreezerForm, self).clean()
        cleaned_data = self.cleaned_data
        cc = cleaned_data.get('cell_capacity', None)
        bw = cleaned_data.get('box_width', None)
        for cap in ('shelf_capacity', 'rack_capacity', 'drawer_capacity',
                    'box_capacity', 'cell_capacity'):
            cn = cleaned_data.get(cap, None)
            if cn is not None:
                if isinstance(cn, int):
                    if cn > 255:
                        msg = 'Value entered too large.'
                        self._errors[cap] = self.error_class([msg])
                        del cleaned_data[cap]
                    elif cn < 1:
                        msg = 'Value must be a positive integer.'
                        self._errors[cap] = self.error_class([msg])
                        del cleaned_data[cap]
                else:
                    msg = 'Value must be a positive integer.'
                    self._errors[cap] = self.error_class([msg])
                    del cleaned_data[cap]
        if cc and bw:
            if cc % bw:
                msg = 'Cell capacity must be divisible by the box width.'
                self._errors['box_width'] = self.error_class([msg])
                del cleaned_data['box_width']
        return cleaned_data

    class Meta:
        model = Freezer
        exclude = ('occupied', 'unoccupied', 'percent_free',)
        widgets = {
            'shelf_capacity': forms.TextInput(attrs={'class': 'span1'}),
            'rack_capacity': forms.TextInput(attrs={'class': 'span1'}),
            'drawer_capacity': forms.TextInput(attrs={'class': 'span1'}),
            'box_capacity': forms.TextInput(attrs={'class': 'span1'}),
            'box_width': forms.TextInput(attrs={'class': 'span1'}),
            'cell_capacity': forms.TextInput(attrs={'class': 'span1'}),
        }


class FreezerEditForm(ModelForm):

    class Meta:
        model = Freezer
        exclude = (
            'occupied',
            'unoccupied',
            'percent_free',
            'layout_string',
            'shelf_capacity',
            'rack_capacity',
            'drawer_capacity',
            'box_capacity',
            'box_width',
            'cell_capacity',
        )


class PILabSupplier(models.Model):
    """Information on client/sample 'owner'"""
    first_name = models.CharField(max_length=100, help_text="*")
    last_name = models.CharField(blank=True, max_length=100)
    email = models.EmailField(blank=True)
    pi_lab_supplier = models.CharField("PI/Lab/Supplier", max_length=100, help_text="*")
    organization = models.CharField(max_length=100, help_text="*")

    def __unicode__(self):
        return u"%s: %s" % (self.pi_lab_supplier, self.organization)


class PILabSupplierForm(ModelForm):
    class Meta:
        model = PILabSupplier


class SampleType(models.Model):
    """
    The type of sample: protein, antibody, plasmid, etc.
    """
    sample_type = models.CharField(max_length=100)

    def __unicode__(self):
        return u"%s" % self.sample_type


class SampleTypeForm(ModelForm):
    class Meta:
        model = SampleType
        widgets = {
            'sample_type': forms.TextInput(attrs={'class': 'span4'}),
        }


class SampleLocation(models.Model):
    """
    Store details about the location and sample information if occupied.
    """
    SPECIES_CHOICES = (
        ('', '--------'),
        ('C. Elegans', 'C. Elegans'),
        ('Danio rerio', 'Danio rerio'),
        ('Drosophila', 'Drosophila'),
        ('E. coli', 'E. coli'),
        ('Goat', 'Goat'),
        ('Hamster', 'Hamster'),
        ('Human', 'Human'),
        ('Mouse', 'Mouse'),
        ('Rabbit', 'Rabbit'),
        ('Rat', 'Rat'),
        ('S. frugiperda', 'S. frugiperda'),
        ('Trichopulsia ni', 'Trichopulsia ni'),
    )

    CELL_CHOICES = (
        ('', '--------'),
        ('293-6E', '293-6E'),
        ('293F', '293F'),
        ('293T', '293T'),
        ('BL-21(DE3)', 'BL-21(DE3)'),
        ('CHO', 'CHO'),
        (u'DH-\u03B1', u'DH-\u03B1'),
        ('E. coli', 'E. coli'),
        ('Hi5', 'Hi5'),
        ('Jurkat', 'Jurkat'),
        ('Neuro2A', 'Neuro2A'),
        ('PC12', 'PC12'),
        ('SF9', 'SF9'),
        ('TOP-10', 'TOP-10'),
    )
    # Location information
    occupied = models.NullBooleanField(default=False)
    freezer = models.ForeignKey(Freezer)
    address = models.BigIntegerField()
    box_width = models.IntegerField()
    cell_capacity = models.IntegerField()

    # Sample information
    name = models.CharField(null=True, max_length=100)
    aliquot_number = models.IntegerField(blank=True, null=True)
    solvent = models.CharField(blank=True, null=True, max_length=100)
    sample_type = models.ForeignKey(SampleType, null=True)
    species = models.CharField(blank=True, null=True, max_length=100,
                               choices=SPECIES_CHOICES)
    host_cell_name = models.CharField(blank=True, null=True,
                                      max_length=100,
                                      choices=CELL_CHOICES)
    user = models.ForeignKey(User, null=True)
    pi_lab_supplier = models.ForeignKey(PILabSupplier, null=True)
    catalog_number = models.CharField(blank=True, null=True, max_length=100)
    date_added = models.DateField(null=True, default=datetime.today)
    date_removed = models.DateField(blank=True, null=True)
    production_date = models.DateField(null=True,
                                       default=datetime.today)
    concentration = models.FloatField(null=True,

Freezers3/templates/freezers/add_freezer.html
{% extends "base.html" %}

{% block title %}Add Freezer{% endblock %}

{% block header %}Add Freezer{% endblock %}

{% block content %}
{% if request.user.is_superuser %}
  <form class="form-horizontal" method="post" 
        action={% url freezers.views.add_freezer %}>
    {% csrf_token %}
    <fieldset>
      {% for field in form %}
        <div class="control-group">
          {% if field.errors %}
            <div class="alert alert-error">
              {{ field.errors }}
            </div>
          {% endif %}
          <label class="control-label" for="id_{{ field.name }}">
            {{ field.label }}
          </label>
          <div class="controls">
            {{ field }}
            <span class="help-inline">{{ field.help_text }}</span>
          </div>
        </div>
      {% endfor %}
      <div class="controls">
        <p>&#42; Required field</p>
        <input class="btn btn-primary" type="submit" value="Add Freezer" />
      </div>
    </fieldset>
  </form>
{% else %}
  <div class-"span8">
    <div class="alert alert-info">
      <p>
        Contact administrator to add a new freezer.
      </p>
    </div>
  </div>
{% endif %}
{% endblock %}

Freezers3/templates/freezers/add_supplier.html
{% extends "base.html" %}

{% block title %}Add Supplier{% endblock %}

{% block header %}Add Supplier{% endblock %}

{% block content %}
<div class="row">
  <div class="span8">
    <div class="alert alert-info">
      <p id="box-help-text">
        Use the supplier field to describe the origins of the samples.<br />
        A supplier could be a company, collaborator, or researcher in the lab.
      </p>
    </div> 
  </div>
</div>
<form class="form-horizontal" method="post" 
      action="./?next={{ redirect_to }}">
  {% csrf_token %}
  <fieldset>
    {% for field in form %}
      <div class="control-group">
        {% if field.errors %}
          <div class="alert alert-error">
            {{ field.errors }}
          </div>
        {% endif %}
        <label class="control-label" for="id_{{ field.name }}">
          {{ field.label }}
        </label>
        <div class="controls">
          {{ field }}
          <span class="help-inline">{{ field.help_text }}</span>
        </div>
      </div>
    {% endfor %}
    <div class="controls">
      <p>&#42; Required field</p>
      <input class="btn btn-primary" type="submit" value="Add" />
    </div>
  </fieldset>
</form>
{% endblock %}

Freezers3/templates/freezers/base_box_sample_table.html
{% if samples %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date Added</th>
        <th>Location</th>
        <th>User</th>
        <th>Type</th>
        <th>PI/Lab/Supplier</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      {% for s in samples %}
        <tr id="row{{ s.cell_location }}">
          <td>
            <a href={% url freezers.views.sample_detail s.id %}
                title="Click here to edit/move/view sample">
              {{ s.name }}
            </a>
          </td>
          <td>{{ s.date_added|date:"SHORT_DATE_FORMAT" }}</td>
          <td class="location {{ s.box_width }} {{ s.cell_capacity }}"
              title="Click to toggle between alphanumeric and numeric cell ids">{{ s.cell_location_name }}</td>
          <td>{{ s.user.get_full_name }}</td>
          <td>{{ s.sample_type }}</td>
          <td>
            <a href={% url freezers.views.supplier_detail s.pi_lab_supplier.id %}
                title="Click here to edit/view supplier">
              {{ s.pi_lab_supplier }}
            </a>
          </td>
          <td>
            <a class="btn btn-mini"
               href={% url freezers.views.edit_sample s.id %}
               title="Edit sample">
              <i class="icon-edit"></i>
            </a>
            <a class="btn btn-danger btn-mini"
               href="{% url freezers.views.remove_sample_from_index s.id %}?next={% firstof request.path '/freezers/samples/' %}"
               title="Remove sample">
              <i class="icon-trash icon-white"></i>
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endif %}

Freezers3/templates/freezers/edit_sample.html
{% extends "base.html" %}

{% block title %}Edit Sample{% endblock %}
{% block stylesheets %}
<link type="text/css" href="/static/css/jquery-ui-1.8.16.custom.css" rel="stylesheet" />
{% endblock %}
{% block javascripts %}
<script type="text/javascript" src="/static/js/jquery-ui-1.8.16.custom.min.js"></script>
<script type="text/javascript">
$(function() {
  $("#id_production_date").datepicker({dateFormat: 'yy-mm-dd'});
  $("#id_date_added").datepicker({dateFormat: 'yy-mm-dd'});
  $("#id_date_removed").datepicker({dateFormat: 'yy-mm-dd'});
});
</script>
{% endblock %}

{% block header %}Edit Sample{% endblock %}

{% block content %}
<form class="form-horizontal" method="post" 
      action={% url freezers.views.edit_sample sid %}>
  {% csrf_token %}
  <fieldset>
    {% for field in form %}
	    <div class="control-group">
        {% if field.errors %}
          <div class="alert alert-error">
            {{ field.errors }}
          </div>
        {% endif %}
        <label class="control-label" for="id_{{ field.name }}">
          {{ field.label }} 
        </label>
        <div class="controls">
          {{ field }}
          <span class="help-inline">{{ field.help_text }}</span>
        </div>
      </div>
    {% endfor %}
    {% for mfield in msgform %}
      <div class="control-group">
        {% if mfield.errors %}
          <div class="alert alert-error">    
            {{ mfield.errors }}
          </div>
        {% endif %}
        <label class="control-label" for="id_{{ field_name }}">
          {{ mfield.label_tag }} 
        </label>
        <div class="controls">
          {{ mfield }}
          <span class="help-inline">{{ mfield.help_text }}</span>
        </div>
      </div>
    {% endfor %}
    <div class="controls">
      <p>&#42; Required field</p>
      <input class="btn btn-primary" type="submit" value="Save" />
    </div>
  </fieldset>
</form>
{% endblock %}

Freezers3/templates/freezers/edit_supplier.html
{% extends "base.html" %}

{% block title %}Edit Supplier{% endblock %}

{% block header %}Edit Supplier{% endblock %}

{% block content %}
<form class="form-horizontal" method="post" action={% url freezers.views.edit_supplier supplier_id %}>
  {% csrf_token %}
  <fieldset>
    {% for field in form %}
      <div class="control-group">
          {% if field.errors %}
            <div class="alert alert-error">
              {{ field.errors }}
            </div>
          {% endif %}
          <label class="control-label" for="id_{{ field.name }}">
            {{ field.label }} 
          </label>
          <div class="controls">
            {{ field }}
            <span class="help-inline">{{ field.help_text }}</span>
          </div>
      </div>
    {% endfor %}
    <div class="controls">
      <p>&#42; Required field</p>
      <input class="btn btn-primary" type="submit" value="Save" />
    </div>
  </fieldset>
</form>
{% endblock %}

Freezers3/templates/freezers/remodel_freezer.html
{% extends "base.html" %}

{% block title %}Remodel Freezer{% endblock %}

{% block header %}Remodel Freezer{% endblock %}

{% block content %}
<p>
  Remodel Freezer {{ fname }}
  {% if sid %}
    Shelf {{ sid }}
    {% if rid %}
      Rack {{ rid }}
      {% if did %}
        Drawer {{ did }}
        {% if bid %}
          Box {{ bid }}
        {% endif %}
      {% endif %}
    {% endif %}
  {% endif %}
</p>
{% if msg %}
  <p class="errorlist">{{ msg }}</p>
{% endif %}
<form method="post" action="{{ url }}">
  {% csrf_token %}
  {% for field in form %}
    <div class="fieldWrapper">
      {{ field.errors }}
      {{ field.label_tag }} {{ field }}
      <div class="help-text">{{ field.help_text }}</div>
    </div>
  {% endfor %}
  <p class="recfield">&#42; Required field</p>
  <p class="button">
    <input type="submit" value="Edit" />
  </p>
</form>
{% endblock %}