Freezers3/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'Freezers3.views.root_view', name='home'),
    url(r'^accounts/login/$', login),
    url(r'^accounts/logout/$', 'Freezers3.views.logout_view'),
    url(r'^freezers/', include('freezers.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT}),
    )
    urlpatterns += patterns('',
        url(r'^resources/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )
urlpatterns += staticfiles_urlpatterns()

freezers/urls.py
from django.conf.urls.defaults import patterns  # , include, url

urlpatterns = patterns(
    'freezers.views',
    (r'^$', 'freezer_index'),
    (r'^new/$', 'add_freezer'),
    (r'^(?P<freezer_id>\d+)/select-location/$', 'select_sample_location'),
    (r'^(?P<freezer_id>\d+)/select-sample-location/$',
        'select_sample_location'),
    (r'^(?P<freezer_id>\d+)/(?P<address>\d+)/$', 'show_box'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/$',
        'select_box_location'),
    (r'^(?P<freezer_id>\d+)/add-samples/$', 'add_samples_to_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/add-samples/$',
        'add_samples_to_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/add-samples/$',
        'add_samples_to_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/add-samples/$',
        'add_samples_to_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/(?P<cell_id>\d+)/add-samples/$',
        'add_samples_to_freezer'),
    (r'^(?P<freezer_id>\d+)/samples/$', 'sample_index_by_location'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/samples/$',
     'sample_index_by_location'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/samples/$',
     'sample_index_by_location'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/samples/$',
        'sample_index_by_location'),
    (r'^samples/$', 'sample_index'),
    (r'^suppliers/new/$', 'add_supplier'),
    (r'^suppliers/$', 'supplier_index'),
    (r'^sample-type/new/$', 'add_sample_type'),
    (r'^(?P<freezer_id>\d+)/$', 'freezer_detail'),
    (r'^suppliers/(?P<supplier_id>\d+)/$', 'supplier_detail'),
    (r'^samples/(?P<sample_id>\d+)/$', 'sample_detail'),
    (r'^(?P<freezer_id>\d+)/edit/$', 'edit_freezer'),
    (r'^(?P<freezer_id>\d+)/remove/$', 'remove_freezer'),
    (r'^suppliers/(?P<supplier_id>\d+)/edit/$', 'edit_supplier'),
    (r'^samples/(?P<sample_id>\d+)/edit/$', 'edit_sample'),
    (r'^samples/(?P<sample_id>\d+)/move/$', 'move_sample_select_freezer'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^samples/(?P<sample_id>\d+)/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/(?P<cell_id>\d+)/move/(?P<atoa>\d+)/$',
        'move_sample'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/move-box/$',
        'move_box_select_freezer'),
    (r'(?P<box_address>\d+)/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/move-box/$',
        'move_box'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/rearrange-samples/$',
        'rearrange_samples_within_box'),
    (r'^samples/(?P<sample_id>\d+)/(?P<cell_id>\d+)/swap-samples/$', 'swap_samples'),
    (r'^samples/(?P<sample_id>\d+)/remove/$', 'remove_sample_from_index'),
    (r'^samples/(?P<sample_id>\d+)/remove-sample/$', 'remove_sample'),
    (r'^search/$', 'search'),
    (r'^(?P<freezer_id>\d+)/select-region-to-edit/$',
        'select_region_to_edit'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/edit-region/$',
        'edit_freezer_region'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/edit-region/$',
        'edit_freezer_region'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/edit-region/$',
        'edit_freezer_region'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/edit-region/$',
        'edit_freezer_region'),
    (r'^removed/((?P<query>[^/]+)/)?$', 'removed_index'),
    (r'^removed/(?P<removed_id>\d+)/detail/$', 'removed_detail'),
    (r'^removed/(?P<removed_id>\d+)/return/$', 'return_removed_sample'),
    (r'^home/$', 'home_link'),
    (r'^home/(?P<user_id>\d+)/$', 'homepage'),
    (r'^messages/(?P<msg_id>\d+)/delete/$', 'delete_message'),
    (r'^messages/(?P<msg_id>\d+)/reply/$', 'reply_to_message'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/select-samples/$',
        'select_samples_in_box'),
    (r'^move-selected/$',
        'move_selected_samples_select_freezer'),
    (r'^move-selected/(?P<freezer_id>\d+)/$',
        'move_selection'),
    (r'^move-selected/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/$',
        'move_selection'),
    (r'^move-selected/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/$',
        'move_selection'),
    (r'^move-selected/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/$',
        'move_selection'),
    (r'^move-selected/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/$',
        'move_selection'),
    (r'^move-selected/(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/(?P<cell_id>\d+)/$',
        'move_selection'),
    (r'^remove-selected-samples/$', 'remove_selected_samples'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/remodel/$',
        'remodel_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/remodel/$',
        'remodel_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/remodel/$',
        'remodel_freezer'),
    (r'^(?P<freezer_id>\d+)/(?P<shelf_id>\d+)/(?P<rack_id>\d+)/(?P<drawer_id>\d+)/(?P<box_id>\d+)/remodel/$',
        'remodel_freezer'),
    (r'^export-samples/$', 'export_samples'),
    (r'^delete-file/(?P<file_id>\d+)/$', 'delete_file'),
    (r'^(?P<freezer_id>\d+)/(?P<addr>\d+)/name-box/$', 'name_box'),
)

freezers/forms.py
from datetime import datetime
from django import forms
from django.contrib.auth.models import User
from freezers.models import *


class AddSampleForm(forms.Form):
    number_of_aliquots = forms.IntegerField(
        help_text="*",
        widget=forms.TextInput(attrs={'class': 'span1'})
    )
    starting_aliquot_number = forms.IntegerField(
        initial=1,
        help_text="*",
        widget=forms.TextInput(attrs={'class': 'span1'})
    )
    name = forms.CharField(max_length=100, help_text="*")
    solvent = forms.CharField(required=False, max_length=100)
    sample_type = forms.ModelChoiceField(
        queryset=SampleType.objects.order_by('sample_type'),
        help_text="*"
    )
    species = forms.ChoiceField(required=False,
                                choices=SampleLocation.SPECIES_CHOICES)
    host_cell_name = forms.ChoiceField(required=False,
                                       choices=SampleLocation.CELL_CHOICES)
    user = forms.ModelChoiceField(queryset=User.objects.order_by('username'),
                                  help_text="*")
    pi_lab_supplier = forms.ModelChoiceField(
        queryset=PILabSupplier.objects.order_by('pi_lab_supplier'),
        label="PI/Lab/Supplier",
        help_text="*"
    )
    catalog_number = forms.CharField(required=False, max_length=100)
    date_added = forms.DateField(initial=datetime.today, help_text="*")
    production_date = forms.DateField(initial=datetime.today,
                                      help_text="*")
    concentration = forms.FloatField(help_text=u"* in \u03BCg/\u03BCl",
                                     widget=forms.TextInput(attrs={'class': 'span1'}))
    volume = forms.FloatField(help_text=u"* in \u03BCl",
                              widget=forms.TextInput(attrs={'class': 'span1'}))
    comments = forms.CharField(required=False,
                               max_length=500,
                               widget=forms.Textarea(attrs={'class': 'span4'}))


class MoveSampleForm(forms.Form):
    select_freezer = forms.ModelChoiceField(queryset=Freezer.objects,
                                            help_text="*")
    apply_to_aliquots = forms.BooleanField(
        required=False,
        initial=False,
        help_text="Check to move remaining aliquots."
    )


class MoveBoxForm(forms.Form):
    select_freezer = forms.ModelChoiceField(queryset=Freezer.objects,
                                            help_text="*")


class SearchSamples(forms.Form):
    SEARCH_CHOICES = (
        ('', '----------'),
        ('name', 'Sample Name'),
        ('sample_type', 'Sample Type'),
        ('species', 'Species'),
        ('host_cell_name', 'Host Cell'),
        ('user', 'Sample User'),
        ('pi_lab_supplier', 'PI/Lab/Supplier'),
        ('catalog_number', 'Catalog Number'),
        ('date_added', 'Date Added'),
        ('production_date', 'Production Date'),
    )
    search = forms.CharField(max_length=50,
                             help_text="*",
                             widget=forms.TextInput(attrs={'class': 'span4'}),
                             label="Search for")
    option = forms.ChoiceField(choices=SEARCH_CHOICES,
                               required=False,
                               label="Add category")


class ChangeFreezerLayout(forms.Form):
    REGION_CHOICES = (
        ('new_rack_capacity', 'Rack Capacity'),
        ('new_drawer_capacity', 'Drawer Capacity'),
        ('new_box_capacity', 'Box Capacity'),
        ('new_cell_capacity', 'Cell Capacity'),
    )
    change = forms.ChoiceField(choices=REGION_CHOICES, help_text="*")
    new_capacity = forms.IntegerField(help_text="*")
    new_box_width = forms.IntegerField(
        required=False,
        help_text="Enter value if changing cell capacity"
    )

    def clean(self):
        cleaned_data = self.cleaned_data
        new_capacity = cleaned_data['new_capacity']
        new_box_width = cleaned_data['new_box_width']
        change = cleaned_data['change']

        if new_box_width and change == 'new_cell_capacity':
            if new_capacity % new_box_width:
                msg = 'Cell capacity must be divisible by the box width.'
                self._errors['new_box_width'] = self.error_class([msg])
                del cleaned_data['new_box_width']
        return cleaned_data


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=80,
                             help_text="*",
                             widget=forms.TextInput(attrs={'class': 'span5'}))


class HeaderSearchForm(forms.Form):
    header_search = forms.CharField(max_length=80)


class ChangeFreezerLayout1(forms.Form):
    """
    Interface to remodel freezer structure.
    """
    each_shelf_should_have = forms.IntegerField(
        help_text="racks",
        widget=forms.TextInput(attrs={'class': 'span1'}),
        required=False
    )
    each_rack_should_have = forms.IntegerField(
        help_text="drawers",
        widget=forms.TextInput(attrs={'class': 'span1'}),
        required=False
    )
    each_drawer_should_have = forms.IntegerField(
        help_text="boxes",
        widget=forms.TextInput(attrs={'class': 'span1'}),
        required=False
    )
    each_box_should_have = forms.IntegerField(
        help_text="cells",
        widget=forms.TextInput(attrs={'class': 'span1'}),
        required=False
    )
    the_box_width_should_be = forms.IntegerField(
        help_text="cells across",
        widget=forms.TextInput(attrs={'class': 'span1'}),
        required=False
    )

    def clean(self):
        cleaned_data = self.cleaned_data
        d = {
            'each_shelf_should_have': cleaned_data.get(
                'each_shelf_should_have', None
            ),
            'each_rack_should_have': cleaned_data.get(
                'each_rack_should_have', None
            ),
            'each_drawer_should_have': cleaned_data.get(
                'each_drawer_should_have', None
            ),
            'each_box_should_have': cleaned_data.get(
                'each_box_should_have', None
            ),
            'the_box_width_should_be': cleaned_data.get(
                'the_box_width_should_be',
                None
            ),
        }
        for k, v in d.iteritems():
            if v:
                if v > 255 or v < 1:
                    msg = "Value must be an integer between 1 and 255"
                    self._errors[k] = self.error_class([msg])
                    del cleaned_data[k]
        if d['each_box_should_have']:
            if d['the_box_width_should_be']:
                if d['each_box_should_have'] % d['the_box_width_should_be']:
                    msg = 'Cell capacity must be divisible by the box width.'
                    self._errors[
                        'the_box_width_should_be'
                    ] = self.error_class([msg])
                    del cleaned_data['the_box_width_should_be']
            else:
                msg = "You need to specify a value for the new box width"
                self._errors[
                    'the_box_width_should_be'
                ] = self.error_class([msg])
                del cleaned_data['the_box_width_should_be']
        return cleaned_data

Freezers3/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required

@login_required
def logout_view(request):
    auth.logout(request)
    return HttpResponseRedirect('/accounts/login/')

def root_view(request):
    if request.user.is_authenticated():
        return redirect('/freezers/home/%s/' % request.user.id)
    return redirect('/accounts/login/')

Freezers3/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Freezer Inventory | {% block title %}{% endblock %}</title>
    {% block meta %}{% endblock %}
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 30px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/static/css/docs.css" rel="stylesheet">
    {% block stylesheets %}{% endblock %}
    <script src="/static/js/jquery-1.7.1.min.js"></script>
    {% block javascripts %}{% endblock %}
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Freezer Inventory</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li>
                <a href="{% url freezers.views.home_link %}">
                  <i class="icon-home icon-white"></i>
                  Home
                </a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-list icon-white"></i>
                  Index 
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url freezers.views.freezer_index %}">
                      Freezers
                    </a>
                  </li>
                  <li>
                    <a href="{% url freezers.views.sample_index %}">
                      Samples
                    </a>
                  </li>
                  <li>
                    <a href="{% url freezers.views.supplier_index %}">
                      Suppliers
                    </a>
                  </li>
                  <li>
                    <a href={% url freezers.views.removed_index %}>
                      Removed Samples
                    </a>
                  </li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-plus icon-white"></i>
                  Add 
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url freezers.views.add_freezer %}"
                         title="Create a new freezer">
                      Add Freezers
                    </a>
                  </li>
                  <li>
                    <a href="{% url freezers.views.freezer_index %}?orig=add-samples">
                      Add Samples
                    </a>
                  </li>
                  <li>
                    <a href="{% url freezers.views.add_sample_type %}?next={% firstof request.path '/freezers/' %}">
                      Add Sample Type
                    </a>
                  </li>
                  <li>
                    <a href="{% url freezers.views.add_supplier %}?next={% firstof request.path '/freezers' %}">
                      Add Suppliers
                    </a>
                  </li>
                </ul>
              </li>
              {% if request.user.is_superuser %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-wrench icon-white"></i>
                    Admin
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <a href="/admin/">Homepage</a>
                    </li>
                    <li>
                      <a href="/admin/auth/user/">Users</a>
                    </li>
                    <li>
                      <a href="/admin/freezers/freezer/">Freezers</a>
                    </li>
                    <li>
                      <a href="/admin/freezers/samplelocation/">Sample Locations</a>
                    </li>
                    <li>
                      <a href="/admin/freezers/sampletype/">Sample Types</a>
                    </li>
                    <li>
                      <a href="/admin/freezers/pilabsupplier/">Suppliers</a>
                    </li>
                  </ul>
                </li>
              {% endif %}
            </ul>
          </div>
          <form class="navbar-search pull-right" method="post"
                action="{% url freezers.views.search %}">
            {% csrf_token %}
            <fieldset>
              <i class="icon-search icon-white"></i>
              <input id="id_header_search" type="text" 
                     class="search-query span3" name="header_search"
                     maxlength="80" placeholder="Search"> 
            </fieldset>
          </form>
          <ul class="nav pull-right">
            <li>
              <a href="{% url views.logout_view %}">
                <i class="icon-off icon-white"></i>
                Logout
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <header class="jumbotron masthead" id="overview">
        <h1>{% block header %}{% endblock %}</h1>
      </header>
      {% block content %}{% endblock %}
    </div>
    <script src="/static/js/bootstrap.js"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

Freezers3/templates/login_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Freezer Inventory | {% block title %}{% endblock %}</title>
    <meta name="author" content="Claude Rogers">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="/static/css/docs.css" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <header class="jumbotron masthead" id="overview">
        <h1>{% block header %}{% endblock %}</h1>
      </header>
      {% block content %}{% endblock %}
    </div>
    <script src="/static/js/jquery-1.7.1.min.js"></script>
    <script src="/static/js/bootstrap.js"></script>
  </body>
</html>